# Exercise 1

### Step 1. Go to https://www.kaggle.com/openfoodfacts/world-food-facts/data

### Step 2. Download the dataset to your computer and unzip it.

In [1]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load

# Download latest version
path = kagglehub.dataset_download("openfoodfacts/world-food-facts")

print("Path to dataset files:", path)
# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "openfoodfacts/world-food-facts",
  "en.openfoodfacts.org.products.tsv",
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/Users/turkialomran/Desktop/SDAIA_Bootcamp/AAI/AAI/content/W2/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/turkialomran/.cache/kagglehub/datasets/openfoodfacts/world-food-facts/versions/5

/var/folders/bj/j64lfc0j2n13lty_b3dm3frw0000gn/T/ipykernel_34700/3136906175.py:13: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to /Users/turkialomran/.cache/kagglehub/datasets/openfoodfacts/world-food-facts/versions/5/en.openfoodfacts.org.products.tsv...

100%|██████████| 109M/109M [00:45<00:00, 2.48MB/s]

Extracting zip of en.openfoodfacts.org.products.tsv...

/Users/turkialomran/Desktop/SDAIA_Bootcamp/AAI/AAI/content/W2/.venv/lib/python3.12/site-packages/kagglehub/pandas_datasets.py:92: DtypeWarning: Columns (0: code, 1: created_t, 2: last_modified_t, 3: manufacturing_places, 4: manufacturing_places_tags, 5: emb_codes, 6: emb_codes_tags, 7: first_packaging_code_geo, 8: cities, 9: cities_tags, 10: allergens_en, 11: traces, 12: traces_tags, 13: traces_en, 14: ingredients_from_palm_oil_tags) have mixed types. Specify dtype option on import or set low_memory=False.
  result = read_function(

First 5 records:     code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...
1   4530  http://world-en.openfoodfacts.org/product/0000...
2   4559  http://world-en.openfoodfacts.org/product/0000...
3  16087  http://world-en.openfoodfacts.org/product/0000...
4  16094  http://world-en.openfoodfacts.org/product/0000...

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)
2      1489069957   2017-03-09T14:32:37Z                         Peanuts
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta

  generic_name quantity  ... fruits-vegetables-nuts_100g  \
0          NaN      1kg  ...                         NaN
1          NaN      NaN  ...                         NaN
2          NaN      NaN  ...                         NaN
3          NaN      NaN  ...                         NaN
4          NaN      NaN  ...                         NaN

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN
1                                  NaN                              NaN
2                                  NaN                              NaN
3                                  NaN                              NaN
4                                  NaN                              NaN

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN
1        NaN             NaN                   NaN                    14.0
2        NaN             NaN                   NaN                     0.0
3        NaN             NaN                   NaN                    12.0
4        NaN             NaN                   NaN                     NaN

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g
0                     NaN                 NaN                 NaN
1                    14.0                 NaN                 NaN
2                     0.0                 NaN                 NaN
3                    12.0                 NaN                 NaN
4                     NaN                 NaN                 NaN

[5 rows x 163 columns]

### Step 3. Use the tsv file and assign it to a dataframe called food

In [ ]:
import pandas as pd
#already read in the kaggle cell, tsv can be read with pd.read_csv(path, sep='\t')

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 4. See the first 5 entries

In [3]:
df.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 5. What is the number of observations in the dataset?

In [7]:
print(f'Number of observation in the data is {len(df)}')

Number of observation in the data is 356027

### Step 6. What is the number of columns in the dataset?

In [21]:
print(f'Number of columns in the dataframe is {len(df.columns)}')
#print(f'Number of columns in the dataframe is {len(df.shape[1])}')

Number of columns in the dataframe is 163

### Step 7. Print the name of all the columns.

In [ ]:
for i, column in enumerate(df.columns):
    print(f'column {i+1}: {column}')

# i chose this way so it is more readable than a big list

column 1: code
column 2: url
column 3: creator
column 4: created_t
column 5: created_datetime
column 6: last_modified_t
column 7: last_modified_datetime
column 8: product_name
column 9: generic_name
column 10: quantity
column 11: packaging
column 12: packaging_tags
column 13: brands
column 14: brands_tags
column 15: categories
column 16: categories_tags
column 17: categories_en
column 18: origins
column 19: origins_tags
column 20: manufacturing_places
column 21: manufacturing_places_tags
column 22: labels
column 23: labels_tags
column 24: labels_en
column 25: emb_codes
column 26: emb_codes_tags
column 27: first_packaging_code_geo
column 28: cities
column 29: cities_tags
column 30: purchase_places
column 31: stores
column 32: countries
column 33: countries_tags
column 34: countries_en
column 35: ingredients_text
column 36: allergens
column 37: allergens_en
column 38: traces
column 39: traces_tags
column 40: traces_en
column 41: serving_size
column 42: no_nutriments
column 43: additives_n
column 44: additives
column 45: additives_tags
column 46: additives_en
column 47: ingredients_from_palm_oil_n
column 48: ingredients_from_palm_oil
column 49: ingredients_from_palm_oil_tags
column 50: ingredients_that_may_be_from_palm_oil_n
column 51: ingredients_that_may_be_from_palm_oil
column 52: ingredients_that_may_be_from_palm_oil_tags
column 53: nutrition_grade_uk
column 54: nutrition_grade_fr
column 55: pnns_groups_1
column 56: pnns_groups_2
column 57: states
column 58: states_tags
column 59: states_en
column 60: main_category
column 61: main_category_en
column 62: image_url
column 63: image_small_url
column 64: energy_100g
column 65: energy-from-fat_100g
column 66: fat_100g
column 67: saturated-fat_100g
column 68: -butyric-acid_100g
column 69: -caproic-acid_100g
column 70: -caprylic-acid_100g
column 71: -capric-acid_100g
column 72: -lauric-acid_100g
column 73: -myristic-acid_100g
column 74: -palmitic-acid_100g
column 75: -stearic-acid_100g
column 76: -arachidic-acid_100g
column 77: -behenic-acid_100g
column 78: -lignoceric-acid_100g
column 79: -cerotic-acid_100g
column 80: -montanic-acid_100g
column 81: -melissic-acid_100g
column 82: monounsaturated-fat_100g
column 83: polyunsaturated-fat_100g
column 84: omega-3-fat_100g
column 85: -alpha-linolenic-acid_100g
column 86: -eicosapentaenoic-acid_100g
column 87: -docosahexaenoic-acid_100g
column 88: omega-6-fat_100g
column 89: -linoleic-acid_100g
column 90: -arachidonic-acid_100g
column 91: -gamma-linolenic-acid_100g
column 92: -dihomo-gamma-linolenic-acid_100g
column 93: omega-9-fat_100g
column 94: -oleic-acid_100g
column 95: -elaidic-acid_100g
column 96: -gondoic-acid_100g
column 97: -mead-acid_100g
column 98: -erucic-acid_100g
column 99: -nervonic-acid_100g
column 100: trans-fat_100g
column 101: cholesterol_100g
column 102: carbohydrates_100g
column 103: sugars_100g
column 104: -sucrose_100g
column 105: -glucose_100g
column 106: -fructose_100g
column 107: -lactose_100g
column 108: -maltose_100g
column 109: -maltodextrins_100g
column 110: starch_100g
column 111: polyols_100g
column 112: fiber_100g
column 113: proteins_100g
column 114: casein_100g
column 115: serum-proteins_100g
column 116: nucleotides_100g
column 117: salt_100g
column 118: sodium_100g
column 119: alcohol_100g
column 120: vitamin-a_100g
column 121: beta-carotene_100g
column 122: vitamin-d_100g
column 123: vitamin-e_100g
column 124: vitamin-k_100g
column 125: vitamin-c_100g
column 126: vitamin-b1_100g
column 127: vitamin-b2_100g
column 128: vitamin-pp_100g
column 129: vitamin-b6_100g
column 130: vitamin-b9_100g
column 131: folates_100g
column 132: vitamin-b12_100g
column 133: biotin_100g
column 134: pantothenic-acid_100g
column 135: silica_100g
column 136: bicarbonate_100g
column 137: potassium_100g
column 138: chloride_100g
column 139: calcium_100g
column 140: phosphorus_100g
column 141: iron_100g
column 142: magnesium_100g
column 143: zinc_100g
column 144: copper_100g
column 145: manganese_100g
column 146: fluoride_100g
column 147: selenium_100g
column 148: chromium_100g
column 149: molybdenum_100g
column 150: iodine_100g
column 151: caffeine_100g
column 152: taurine_100g
column 153: ph_100g
column 154: fruits-vegetables-nuts_100g
column 155: fruits-vegetables-nuts-estimate_100g
column 156: collagen-meat-protein-ratio_100g
column 157: cocoa_100g
column 158: chlorophyl_100g
column 159: carbon-footprint_100g
column 160: nutrition-score-fr_100g
column 161: nutrition-score-uk_100g
column 162: glycemic-index_100g
column 163: water-hardness_100g

### Step 8. What is the name of 105th column?

In [ ]:
print(f'105th column name: {df.columns[104]}')

105th column name: -glucose_100g

### Step 9. What is the type of the observations of the 105th column?

In [ ]:
df['-glucose_100g'].dtype

dtype('float64')

### Step 10. How is the dataset indexed?

### Step 11. What is the product name of the 19th observation?